apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rundeck
  namespace: argocd
  labels:
    Product: DevOps
    ProductComponents: ArgoApplicationSet
    Region: br
    Environment: main
    kind: helm
    type: declarative
spec:
  project: default
  source:
    repoURL: https://github.com/dgolive/rundeck-helm.git
    targetRevision: main
    path: helm/rundeck
    helm:
      releaseName: rundeck
      parameters:
      - name: clusterName
        value: rundeck
  destination:
    server: https://kubernetes.default.svc
    #namespace: rundeck
 