apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rundeck-dev
  namespace: argocd
  labels:
    Product: DevOps
    ProductComponents: ArgoApplicationSet
    Region: br
    Environment: dev
    kind: helm
    type: declarative
spec:
  project: default
  source:
    repoURL: https://github.com/dgolive/rundeck-helm.git
    targetRevision: dev
    path: rundeck
    helm:
      releaseName: rundeck
      parameters:
      - name: clusterName
        value: rundeck
  destination:
    server: https://kubernetes.default.svc
  
 