kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rundeck-cluster-admin
subjects:
- kind: ServiceAccount
  name: rundeck
  namespace: rundeck
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io