apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rundeck.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rundeck.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rundeck.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rundeck.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rundeck.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
            - name: RUNDECK_GRAILS_URL  
              value: http://localhost:4440
            - name: RUNDECK_SERVER_FORWARDED
              value: "true"
            - name: RUNDECK_LOGGING_STRATEGY
              value: CONSOLE       
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4440
              protocol: TCP
          lifecycle:
            postStart:
              exec:
                command: command: ["/bin/bash", "-c", "script/postStart.sh"]
          livenessProbe:
            httpGet:
              path: /
              port: 4440
            initialDelaySeconds: 500
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /
              port: 4440
            initialDelaySeconds: 120
            periodSeconds: 60
          volumeMounts:
            - mountPath: /home/rundeck/server/data
              name: data
            - mountPath: /home/rundeck/script
              name: script
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: script
          
