apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rundeck-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/app/rundeck-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rundeck-claim1
  name: rundeck-claim1
  namespace: rundeck
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
